version: '2.1'

volumes:
  peer0.secblock.technology:
  peer1.secblock.technology:

networks:
  secblock-blockchain:   

services: 

  peer0.secblock.technology:
    container_name: peer0.secblock.technology
    image: hyperledger/fabric-peer:2.2.3
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=busy-network_secblock-blockchain
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.secblock.technology
      - CORE_PEER_ADDRESS=peer0.secblock.technology:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.secblock.technology:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.secblock.technology:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.secblock.technology:7051
      - CORE_PEER_LOCALMSPID=secblockMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ./organizations/peerOrganizations/secblock.technology/peers/peer0.secblock.technology/msp:/etc/hyperledger/fabric/msp
        - ./organizations/peerOrganizations/secblock.technology/peers/peer0.secblock.technology/tls:/etc/hyperledger/fabric/tls
        - peer0.secblock.technology:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - secblock-blockchain

  peer1.secblock.technology:
    container_name: peer1.secblock.technology
    image: hyperledger/fabric-peer:2.2.3
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=busy-network_secblock-blockchain
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer1.secblock.technology
      - CORE_PEER_ADDRESS=peer1.secblock.technology:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer1.secblock.technology:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.secblock.technology:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.secblock.technology:9051
      - CORE_PEER_LOCALMSPID=secblockMSP
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ./organizations/peerOrganizations/secblock.technology/peers/peer1.secblock.technology/msp:/etc/hyperledger/fabric/msp
        - ./organizations/peerOrganizations/secblock.technology/peers/peer1.secblock.technology/tls:/etc/hyperledger/fabric/tls
        - peer1.secblock.technology:/var/hyperledger/production 
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - secblock-blockchain

  
